FROM golang:latest

RUN apt -y update

RUN apt -y install --no-install-recommends \
    systemd \
    git \
    tree \
    curl \
    nano \
    python3-pip \
    unzip \
    tar \
    gzip \
    make \
    file

RUN apt -y clean all
