name: Unit Test
on:
  push:
    branches:
      - main
  pull_request_review:
    types: 
      - submitted

permissions:
  id-token: write
  contents: read

jobs:
  unit-test:
    runs-on: ubuntu-latest
    if: |
      (
        github.event_name == 'push' ||
        (
          ( github.event_name == 'pull_request_review' ) &&
          ( github.event.review.state == 'approved' || github.event.review.body == 'TRIGGER_CHECKS')
        )
      )

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up build environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run unit tests
        run: |
          go test -v -cover -coverprofile=coverage.out -json -race .